services:
  - type: web
    name: kit-collective-frontend
    env: static
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    staticPublishPath: build
    pullRequestPreviewsEnabled: true
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: "https://kit-collective-backend.onrender.com"
